# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telectapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=255)),
                ('phone_code_hash', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
