# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telectapi', '0005_auto_20171113_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='are_collecting',
            field=models.BooleanField(default=False),
        ),
    ]
