# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_auto_20171108_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_fm_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='last_fm_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
