# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_auto_20171108_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_fm_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_fm_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
