# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_auto_20171108_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_fm_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
