# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_auto_20171108_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='destination_data',
            field=django_mysql.models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='destination_type',
            field=models.CharField(choices=[('TG', 'Telegram')], default='TG', max_length=2),
        ),
    ]
