# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:41
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_auto_20171108_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='destination_data',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
